import { useEffect, useState } from "react";
import { Card, FormField, Loader } from "../components";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => (
      <Card
        key={post._id}
        {...post}
        className="hover:shadow-lg transition-shadow duration-300 bg-[#1e1e1e] text-white rounded-lg"
      />
    ));
  }
  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase text-center">
      {title}
    </h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([]);
  const [searchText, setSearchText] = useState("");
  const [searchedResults, setSearchedResults] = useState([]);
  const [searchTimeout, setSearchTimeout] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      try {
        const response = await fetch(
          "https://imagegeneratingwebsite.onrender.com/api/v1/post",
          {
            method: "GET",
            headers: {
              "Content-Type": "application/json",
            },
          }
        );
        if (response.ok) {
          const result = await response.json();
          setAllPosts(result.data.reverse());
        }
      } catch (error) {
        alert("An unexpected error occurred: " + error.message);
      } finally {
        setLoading(false);
      }
    };

    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    const newValue = e.target.value;
    setSearchText(newValue);

    setSearchTimeout(
      setTimeout(() => {
        const searchResults = allPosts.filter(
          (item) =>
            item.name.toLowerCase().includes(newValue.toLowerCase()) ||
            item.prompt.toLowerCase().includes(newValue.toLowerCase())
        );
        setSearchedResults(searchResults);
      }, 500)
    );
  };

  return (
    <section className="max-w-full mx-auto p-6 bg-[#121212] min-h-screen">
      <div className="text-center">
        <h1 className="font-extrabold text-white text-[36px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#9a9a9a] text-[18px] max-w-[500px] mx-auto">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>

      <div className="mt-16">
        <FormField
          LabelName="Search Posts"
          type="text"
          name="text"
          placeholder="Search posts"
          value={searchText}
          handleChange={handleSearchChange}
          className="border border-gray-600 text-white rounded-lg p-2 shadow-sm focus:ring-2 focus:ring-[#6449ff]"
        />
      </div>

      <div className="mt-10 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8 items-center">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader className="animate-spin text-white" />
          </div>
        ) : (
          <>
            {searchText ? (
              <RenderCards
                data={searchedResults}
                title="No Search Results Found"
              />
            ) : (
              <RenderCards data={allPosts} title="No Posts Yet" />
            )}
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
